name: Build macOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PROJECT_NAME: BrewServicesMenubar
  SCHEME_NAME: BrewServicesMenubar
  XCODE_VERSION: 15.4

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_${XCODE_VERSION}.app

      - name: Cache Swift packages
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: |
          xcodebuild clean build -project ${PROJECT_NAME}.xcodeproj -scheme ${SCHEME_NAME} -destination 'platform=macOS'

      - name: Archive app
        run: |
          xcodebuild -project ${PROJECT_NAME}.xcodeproj -scheme ${SCHEME_NAME} -configuration Release archive -archivePath $PWD/build/${PROJECT_NAME}.xcarchive

      - name: Export app
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/${PROJECT_NAME}.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build

      - name: Zip .app for upload
        run: |
          cd $PWD/build
          zip -r ${{ env.PROJECT_NAME }}.zip ${{ env.PROJECT_NAME }}.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}
          path: build/${{ env.PROJECT_NAME }}.zip
        if: success()

      - name: Upload build directory (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: build-directory-contents
          path: $PWD/build
        if: failure()
